// Code generated by goctl. DO NOT EDIT.
// Source: pay.proto

package server

import (
	"context"

	"goZeroShopMall/apps/pay/rpc/pay/internal/logic"
	"goZeroShopMall/apps/pay/rpc/pay/internal/svc"
	"goZeroShopMall/apps/pay/rpc/pay/pay"
)

type PayServer struct {
	svcCtx *svc.ServiceContext
	pay.UnimplementedPayServer
}

func NewPayServer(svcCtx *svc.ServiceContext) *PayServer {
	return &PayServer{
		svcCtx: svcCtx,
	}
}

func (s *PayServer) Ping(ctx context.Context, in *pay.Request) (*pay.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
