// Code generated by goctl. DO NOT EDIT.
// Source: reply.proto

package replyclient

import (
	"context"

	"goZeroShopMall/apps/reply/rpc/reply/reply"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = reply.Request
	Response = reply.Response

	Reply interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultReply struct {
		cli zrpc.Client
	}
)

func NewReply(cli zrpc.Client) Reply {
	return &defaultReply{
		cli: cli,
	}
}

func (m *defaultReply) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := reply.NewReplyClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
