// Code generated by goctl. DO NOT EDIT.
// Source: product.proto

package server

import (
	"context"

	"goZeroShopMall/apps/product/rpc/product/internal/logic"
	"goZeroShopMall/apps/product/rpc/product/internal/svc"
	"goZeroShopMall/apps/product/rpc/product/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) Ping(ctx context.Context, in *product.Request) (*product.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
