// Code generated by goctl. DO NOT EDIT.
// Source: reply.proto

package server

import (
	"context"

	"goZeroShopMall/apps/reply/rpc/reply/internal/logic"
	"goZeroShopMall/apps/reply/rpc/reply/internal/svc"
	"goZeroShopMall/apps/reply/rpc/reply/reply"
)

type ReplyServer struct {
	svcCtx *svc.ServiceContext
	reply.UnimplementedReplyServer
}

func NewReplyServer(svcCtx *svc.ServiceContext) *ReplyServer {
	return &ReplyServer{
		svcCtx: svcCtx,
	}
}

func (s *ReplyServer) Ping(ctx context.Context, in *reply.Request) (*reply.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
