// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"goZeroShopMall/apps/order/rpc/order/internal/logic"
	"goZeroShopMall/apps/order/rpc/order/internal/svc"
	"goZeroShopMall/apps/order/rpc/order/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) Ping(ctx context.Context, in *order.Request) (*order.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
