// Code generated by goctl. DO NOT EDIT.
// Source: recommend.proto

package recommendclient

import (
	"context"

	"goZeroShopMall/apps/recommend/rpc/recommend/recommend"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = recommend.Request
	Response = recommend.Response

	Recommend interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultRecommend struct {
		cli zrpc.Client
	}
)

func NewRecommend(cli zrpc.Client) Recommend {
	return &defaultRecommend{
		cli: cli,
	}
}

func (m *defaultRecommend) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := recommend.NewRecommendClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
