// Code generated by goctl. DO NOT EDIT.
// Source: recommend.proto

package server

import (
	"context"

	"goZeroShopMall/apps/recommend/rpc/recommend/internal/logic"
	"goZeroShopMall/apps/recommend/rpc/recommend/internal/svc"
	"goZeroShopMall/apps/recommend/rpc/recommend/recommend"
)

type RecommendServer struct {
	svcCtx *svc.ServiceContext
	recommend.UnimplementedRecommendServer
}

func NewRecommendServer(svcCtx *svc.ServiceContext) *RecommendServer {
	return &RecommendServer{
		svcCtx: svcCtx,
	}
}

func (s *RecommendServer) Ping(ctx context.Context, in *recommend.Request) (*recommend.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
