// Code generated by goctl. DO NOT EDIT.
// Source: pay.proto

package payclient

import (
	"context"

	"goZeroShopMall/apps/pay/rpc/pay/pay"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = pay.Request
	Response = pay.Response

	Pay interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultPay struct {
		cli zrpc.Client
	}
)

func NewPay(cli zrpc.Client) Pay {
	return &defaultPay{
		cli: cli,
	}
}

func (m *defaultPay) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := pay.NewPayClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
